apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dsiem-nats
  labels:
   app: dsiem-nats
spec:
  selector:
    matchLabels:
      app: dsiem-nats
  serviceName: dsiem-nats
  replicas: 1
  template:
    metadata:
      labels:
        app: dsiem-nats
    spec:
      affinity:
        nodeAffinity:
          # must only be run on central appliances, and in frontend
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dsiem-node
                operator: In
                values:
                - "yes"
        # dont put replica on the same node
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - dsiem-nats
              topologyKey: kubernetes.io/hostname
      hostNetwork: false
      containers:
      - name: nats
        image: nats-streaming:0.11.0
        imagePullPolicy: IfNotPresent
