# Gopkg.toml

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  revision = "348b672cd90d8190f8240323e372ecd1e66b59dc"

[[constraint]]
  name = "github.com/kardianos/osext"
  revision = "ae77be60afb1dcacde03767a8c37337fad28ac14"

[[constraint]]
  name = "github.com/teris-io/shortid"
  version = "1.0.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"

[[constraint]]
  name = "github.com/yl2chen/cidranger"
  revision = "928b519e5268fe386d0f7decce320205cc09ca95"
[prune]
  go-tests = true
  unused-packages = true

# [[constraint]]
#  branch = "master"
#  name = "github.com/bbengfort/x"
