filebeat.prospectors:

- input_type: log
  paths:
    - /var/log/external/siem_alarm_events.json
  fields_under_root: true
  fields: { application: siem, siem_data_type: alarm_events }
  tail_files: true
  json.keys_under_root: true
  json.overwrite_keys: true

- input_type: log
  paths:
    - /var/log/external/siem_alarms.json
  fields_under_root: true
  fields: { application: siem, siem_data_type: alarms }
  tail_files: true
  json.keys_under_root: true
  json.overwrite_keys: true

- input_type: log
  paths:
    - /var/log/external/dtester.json
  fields_under_root: true
  fields: { application: dtester }
  tail_files: true
  json.keys_under_root: true
  json.overwrite_keys: true

output:
 logstash:
  # The Logstash hosts
   hosts: ["logstash.default.svc.cluster.local:5001"]

