apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dsiem
  labels:
   app: dsiem
spec:
  selector:
    matchLabels:
      app: dsiem
  serviceName: dsiem
  replicas: 1
  template:
    metadata:
      labels:
        app: dsiem
    spec:
      affinity:
        nodeAffinity:
          # must only be run on central appliances, and in frontend
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dsiem-node
                operator: In
                values:
                - "yes"
        # dont put replica on the same node
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - dsiem
              topologyKey: kubernetes.io/hostname
      hostNetwork: false
      containers:
      - name: dsiem
        securityContext:
          privileged: false
        image: golang
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash" ]
        args: 
        - -c
        - "sleep infinity"
        volumeMounts:
        - name: vol-dsiem
          mountPath: /go/src/dsiem/logs
        env:
        - name: ELASTIC_APM_SERVER_URL
          value: "http://localhost:8200"
        - name: ELASTIC_APM_SERVICE_NAME
          value: "dsiem"
        - name: ELASTIC_APM_ACTIVE
          value: "true"
      - name: apmserver
        image: elastic/apm-server:6.3.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: dsiem-apm-config
          mountPath: /usr/share/apm-server/apm-server.yml
          subPath: apm-server.yml
      - name: logrotate
        image: blacklabelops/logrotate
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: vol-dsiem
          mountPath: /var/log/external
        env:
        - name: LOGROTATE_INTERVAL
          value: "hourly"
        - name: LOGS_DIRECTORIES
          value: "/var/log/external"
      - name: filebeat
        securityContext:
          privileged: false
        image: mgmt:10443/defenxor-appliance/filebeat:6.3.0
        imagePullPolicy: Always
        volumeMounts:
        - name: dsiem-filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: vol-dsiem
          mountPath: /var/log/external
      volumes:
        - name: dsiem-filebeat-config
          configMap:
            name: dsiem-filebeat-config
        - name: dsiem-apm-config
          configMap:
            name: dsiem-apm-config
  volumeClaimTemplates:
  - metadata:
      name: vol-dsiem
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 100Gi
